# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsZQYV1Vdw0vhocEfkEjAmudw9hjL_mJ
"""

import pandas as pd
import numpy as np

def prepare_mortality_data(file_path, year):
    try:
        try:
            df = pd.read_excel(file_path, header=None, engine='xlrd')
        except:
            df = pd.read_excel(file_path, header=None)
    except:
        df = pd.read_html(file_path, header=None)[0]

    df = df.iloc[:, [0, 1, 2]].copy()
    df.columns = ['อายุ', 'ชาย', 'หญิง']
    df['อายุ'] = df['อายุ'].astype(str).str.strip()
    df = df[~df['อายุ'].str.contains('ยอดรวม', na=False)]

    # แปลงข้อความอายุเป็นตัวเลข
    df['อายุ'] = df['อายุ'].str.replace('อายุน้อยกว่า 1 ปี', '0')
    df['อายุ'] = df['อายุ'].str.replace('อายุมากกว่า 100 ปี', '101')
    df['อายุ'] = df['อายุ'].str.replace('อายุ', '').str.replace('ปี', '').str.replace(' ', '')
    df['อายุ'] = pd.to_numeric(df['อายุ'], errors='coerce')

    # ลบแถวที่เป็น NaN ทิ้ง
    df = df.dropna(subset=['อายุ']).copy()
    df['อายุ'] = df['อายุ'].astype(int)

    for col in ['ชาย', 'หญิง']:
        df[col] = df[col].astype(str).str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

    df_melted = pd.melt(
        df,
        id_vars=['อายุ'],
        value_vars=['ชาย', 'หญิง'],
        var_name='Gender_Text',
        value_name='Deaths'
    )

    # แปลงเพศเป็น 0 และ 1 (0=ชาย, 1=หญิง)
    df_melted['Gender'] = df_melted['Gender_Text'].apply(lambda x: 0 if 'ชาย' in x else 1)
    df_melted['Year'] = year

    final_df = df_melted[['Year', 'อายุ', 'Gender', 'Deaths']].rename(columns={'อายุ': 'Age'})
    final_df = final_df.sort_values(by=['Age', 'Gender']).reset_index(drop=True)

    return final_df
all_years_data = []

# วนลูปดึงข้อมูลปี 2561-2568
for year in range(2561, 2569):
    file_name = f"{year}.xls"

    try:
        df_year = prepare_mortality_data(file_name, year)
        all_years_data.append(df_year)
        print(f"✅ สำเร็จ: {file_name} (ได้ข้อมูล {len(df_year)} แถว)")
    except FileNotFoundError:
        print(f"❌ ไม่พบไฟล์ {file_name} ใน Colab")
    except Exception as e:
        print(f"❌ เกิดข้อผิดพลาดกับไฟล์ {file_name}: {e}")


if len(all_years_data) > 0:
    combined_df = pd.concat(all_years_data, ignore_index=True)
    print(f"จำนวนข้อมูลทั้งหมดพร้อมเทรน: {len(combined_df)} แถว")
    display(combined_df.head(10))
else:
    print("\nรวมข้อมูลไม่สำเร็จ")

combined_df.to_csv('cleaned_mortality_data.csv', index=False, encoding='utf-8-sig')

print("บันทึกไฟล์ 'cleaned_mortality_data.csv' ลงในระบบ Colab สำเร็จ!")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, VotingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = combined_df.copy()

X = df[['Year', 'Age', 'Gender']]
y = df['Deaths']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
gb_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
svr_model = SVR(kernel='rbf', C=100, gamma='scale')

ensemble_model = VotingRegressor(
    estimators=[
        ('Random Forest', rf_model),
        ('Gradient Boosting', gb_model),
        ('SVR', svr_model)
    ]
)


ensemble_model.fit(X_train, y_train)
print(" ฝึกสอนเสร็จสมบูรณ์!\n")

y_pred = ensemble_model.predict(X_test)

# ตรวจคำตอบและให้คะแนน (Evaluation)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(" --- ผลการประเมินความแม่นยำ ---")
print(f"1. R-squared (R2 Score): {r2:.4f}")
print(f"   (คะแนนความแม่นยำ ยิ่งใกล้ 1.0 แปลว่า AI อธิบายข้อมูลได้ดีมาก)")
print(f"2. Mean Absolute Error (MAE): {mae:.2f} คน")
print(f"   (โดยเฉลี่ยแล้ว AI ทายจำนวนคนตายคลาดเคลื่อนไปประมาณ {mae:.2f} คนต่อการทาย 1 ครั้ง)")
print(f"3. Root Mean Squared Error (RMSE): {rmse:.2f} คน\n")


new_data = pd.DataFrame([[2569, 70, 0]], columns=['Year', 'Age', 'Gender'])

predicted_deaths = ensemble_model.predict(new_data)
print("--- ตัวอย่างการพยากรณ์อนาคต ---")
print(f"ทายว่า: ประชากร 'ชาย' อายุ '70 ปี' ในปี '2569'")
print(f"จะมีจำนวนผู้เสียชีวิตประมาณ: {int(predicted_deaths[0])} คน")

import pandas as pd
import numpy as np

target_year = 2569

prediction_data = []
for age in range(0, 102):
    for gender in [0, 1]:
        prediction_data.append([target_year, age, gender])

df_predict = pd.DataFrame(prediction_data, columns=['Year', 'Age', 'Gender'])

df_predict['Predicted_Deaths'] = ensemble_model.predict(df_predict)

df_predict['Predicted_Deaths'] = df_predict['Predicted_Deaths'].round().astype(int)

def categorize_age(age):
    if age <= 14:
        return '1. วัยเด็ก (0-14 ปี)'
    elif age <= 59:
        return '2. วัยทำงาน (15-59 ปี)'
    else:
        return '3. วัยชรา (60 ปีขึ้นไป)'

df_predict['Age_Group'] = df_predict['Age'].apply(categorize_age)

df_predict['Gender_Text'] = df_predict['Gender'].map({0: 'ชาย', 1: 'หญิง'})

final_all_ages = df_predict[['Year', 'Age', 'Age_Group', 'Gender_Text', 'Predicted_Deaths']]

summary_by_group = final_all_ages.groupby(['Year', 'Age_Group'])['Predicted_Deaths'].sum().reset_index()


print(f"✅ --- ตารางที่ 1: ผลการพยากรณ์แยกตามทุกช่วงอายุ (ปี {target_year}) ---")
display(final_all_ages) # แสดงข้อมูลทุกอายุและทุกเพศ

print("\n")
print(f"📊 --- ตารางที่ 2: สรุปภาพรวมจำนวนการเสียชีวิตแบ่งตามช่วงวัย (ปี {target_year}) ---")
display(summary_by_group)

import joblib
from google.colab import files


model_filename = 'mortality_ensemble_model.pkl'
joblib.dump(ensemble_model, model_filename)

print(f"บันทึกโมเดลเป็นไฟล์ {model_filename} สำเร็จ!")

files.download(model_filename)