# -*- coding: utf-8 -*-
"""Dog_gemini

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ezPCdeC-TqWRXIue-2yTetCX9B2TG-J
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from google.colab import drive
from google.colab import files
from PIL import Image
import io

drive.mount('/content/drive')

BASE_DIR = '/content/drive/MyDrive/Dog_Dataset' # แก้ไขตรงนี้ถ้า Path ไม่ตรง
TRAIN_DIR = os.path.join(BASE_DIR, 'train')
VAL_DIR = os.path.join(BASE_DIR, 'val')

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode="nearest"
)

val_datagen = ImageDataGenerator()

print("\nกำลังโหลดข้อมูล Train...")
train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

print("\nกำลังโหลดข้อมูล Validation...")
val_generator = val_datagen.flow_from_directory(
    VAL_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

CLASS_NAMES = list(train_generator.class_indices.keys())
NUM_CLASSES = len(CLASS_NAMES)

print("\n" + "="*50)
print(f"✅ จำนวนสายพันธุ์ทั้งหมด: {NUM_CLASSES} สายพันธุ์")
print(f"✅ รายชื่อสายพันธุ์ (ดึงจากโฟลเดอร์จริง): {CLASS_NAMES}")
print(f"📌 Class Mapping (AI จำรหัสตามนี้): {train_generator.class_indices}")
print("="*50 + "\n")

base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(NUM_CLASSES, activation='softmax') # ใช้ NUM_CLASSES อัตโนมัติ
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6, verbose=1),
    ModelCheckpoint('/content/best_dog_model.keras', monitor='val_accuracy', save_best_only=True, verbose=1)
]

EPOCHS = 6

print("🚀 เริ่มทำการเทรนโมเดล...")
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=EPOCHS,
    callbacks=callbacks
)

def predict_dog_breed(image_array):
    """
    รับภาพเข้ามา ทำการ Resize ให้ตรงกับที่โมเดลต้องการ และทำนายสายพันธุ์
    """
    img_resized = tf.image.resize(image_array, IMG_SIZE)
    img_expanded = np.expand_dims(img_resized, axis=0)

    predictions = model.predict(img_expanded)[0]

    top_indices = predictions.argsort()[-3:][::-1]

    print("\nผลการวิเคราะห์ 3 อันดับแรก:")
    for rank, idx in enumerate(top_indices, 1):
        print(f"  {rank}. {CLASS_NAMES[idx]:<20} ความมั่นใจ: {predictions[idx]*100:.2f}%")

    return CLASS_NAMES[top_indices[0]], predictions[top_indices[0]]

print("\n" + "="*50)
print("📤 พร้อมใช้งาน! กรุณากดปุ่มเพื่อเลือกรูปภาพสุนัขที่คุณต้องการทดสอบ...")
print("="*50)

uploaded = files.upload()

for filename, content in uploaded.items():
    print(f"\n🔍 กำลังวิเคราะห์รูปภาพ: {filename}")
    img = Image.open(io.BytesIO(content)).convert("RGB")

    predicted_breed, confidence = predict_dog_breed(np.array(img))

    print(f"\n🎉 สรุป: โมเดลมั่นใจ {confidence*100:.1f}% ว่ารูปนี้น่าจะเป็น '{predicted_breed}'")

def predict_dog_breed(image_array):
    """
    รับภาพเข้ามา ทำการ Resize ให้ตรงกับที่โมเดลต้องการ และทำนายสายพันธุ์
    """
    img_resized = tf.image.resize(image_array, IMG_SIZE)
    img_expanded = np.expand_dims(img_resized, axis=0)

    predictions = model.predict(img_expanded)[0]

    top_indices = predictions.argsort()[-3:][::-1]

    print("\nผลการวิเคราะห์ 3 อันดับแรก:")
    for rank, idx in enumerate(top_indices, 1):
        print(f"  {rank}. {CLASS_NAMES[idx]:<20} ความมั่นใจ: {predictions[idx]*100:.2f}%")

    return CLASS_NAMES[top_indices[0]], predictions[top_indices[0]]

print("\n" + "="*50)
print("📤 พร้อมใช้งาน! กรุณากดปุ่มเพื่อเลือกรูปภาพสุนัขที่คุณต้องการทดสอบ...")
print("="*50)

uploaded = files.upload()

for filename, content in uploaded.items():
    print(f"\n🔍 กำลังวิเคราะห์รูปภาพ: {filename}")
    img = Image.open(io.BytesIO(content)).convert("RGB")

    predicted_breed, confidence = predict_dog_breed(np.array(img))

    print(f"\n🎉 สรุป: โมเดลมั่นใจ {confidence*100:.1f}% ว่ารูปนี้น่าจะเป็น '{predicted_breed}'")